name: Github Metrics SVG
on:
  # Schedule updates (each day 24 点 00 分自动执行一次) 
  # corn 参考 
  # https://img2020.cnblogs.com/blog/740516/202012/740516-20201203230232201-913405527.png
  # https://www.cnblogs.com/xgqfrms/p/14079442.html
  # Runs at 23:59.
  # schedule: [{cron: "59 23 * * *"}]
  # Runs at 23:59, only on Sunday. 每个周末的 23:59 运行一次
  schedule: [{cron: "59 23 * * 0"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: xgqfrms
          template: classic
          base: header, topics, community, repositories, metadata
          config_timezone: Asia/Shanghai
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 666
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: lines, percentage
          plugin_languages_aliases: RenderScript:Rust, XSLT:Haskell
          plugin_languages_limit: 16
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 0%
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_topics_mode: icons
          plugin_people: yes
          plugin_people_types: followers
          plugin_people_limit: 36
          plugin_people_size: 100
