name: GitHub-Profile-3D-Contrib-2022

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:
  push: {branches: ["master"]}

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib-2022
    steps:
      - uses: actions/checkout@v3
      # - uses: actions/checkout@v2
      # - uses: yoshi389111/github-profile-3d-contrib@0.7.0
      - name: GitHub-Profile-3D-Contrib-2022
        uses: xgqfrms/github-profile-3d-contrib-2022@v0.0.1

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name xgqfrms
          git config user.email xgqfrms@xgqfrms.xyz
          git add -A .
          git commit -m "feat: update GitHub 3D Profile 👻"
          git push
